export default {
    FETCH_LEAVE_REQUESTS: 'FETCH_LEAVE_REQUESTS',
    CREATE_LEAVE_REQUEST: 'CREATE_LEAVE_REQUEST',
    DELETE_LEAVE_REQUESTS: 'DELETE_LEAVE_REQUESTS',
    SET_LEAVE_REQUESTS: 'SET_LEAVE_REQUESTS',
    ADD_LEAVE_REQUEST: 'ADD_LEAVE_REQUEST',
    REMOVE_LEAVE_REQUESTS: 'REMOVE_LEAVE_REQUESTS',
    SET_FETCH_LEAVE_REQUESTS_ERROR: 'SET_FETCH_LEAVE_REQUESTS_ERROR',
    CLEAR_FETCH_LEAVE_REQUESTS_ERROR: 'CLEAR_FETCH_LEAVE_REQUESTS_ERROE',
    SET_CREATE_LEAVE_REQUEST_ERROR: 'SET_CREATE_LEAVE_REQUEST_ERROR',
    CLEAR_CREATE_LEAVE_REQUEST_ERROR: 'CLEAR_CREATE_LEAVE_REQUEST_ERROR',
    SET_DELETE_LEAVE_REQUESTS_ERROR: 'SET_DELETE_LEAVE_REQUESTS_ERROR',
    CLEAR_DELETE_LEAVE_REQUESTS_ERRR: 'CLEAR_DELETE_LEAVE_REQUESTS_ERROR'
};